version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
      
    working_directory: ~/repo

    environment:
      MAVEN_OPTS: -Xmx3200m
    
    steps:
      - checkout
      
      - run:
          name: Update the Docker Image
          command: sudo apt-get update

      - run:
          name: Install Docker 1
          command: curl -fsSL https://get.docker.com -o get-docker.sh
          
      - run:
          name: Install Docker 2
          command: sudo sh get-docker.sh
      
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "pom.xml" }}
          - v1-dependencies-

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
        
      # run tests!
      - run: mvn integration-test
      
      - run: docker build --rm=false -t $DOCKER_HUB_USER_ID/account-service .
      
      - deploy:
          name: Publish application to docker hub
          command: |
            docker login -u $DOCKER_HUB_USER_ID -p $DOCKER_HUB_PWD
            docker tag dockerapp_dockerapp $DOCKER_HUB_USER_ID/account-service:$CIRCLE_SHA1
            docker tag dockerapp_dockerapp $DOCKER_HUB_USER_ID/account-service:latest
            docker push $DOCKER_HUB_USER_ID/account-service:$CIRCLE_SHA1
            docker push $DOCKER_HUB_USER_ID/account-service:latest
