version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
      
    working_directory: ~/repo

    environment:
      MAVEN_OPTS: -Xmx3200m
      SHORT_GIT_HASH: $(echo $CIRCLE_SHA1 | cut -c -7)
    
    steps:
      - checkout
      - setup_remote_docker

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
        
      - run: mvn integration-test
      
      - run: docker build -t $DOCKER_HUB_USER_ID/account-service:$CIRCLE_SHA1 .
      
      - deploy:
          name: Publish application to docker hub
          command: |
            docker login -u $DOCKER_HUB_USER_ID -p $DOCKER_HUB_PWD
            docker tag $DOCKER_HUB_USER_ID/account-service:$CIRCLE_SHA1 $DOCKER_HUB_USER_ID/account-service:$SHORT_GIT_HASH
            docker tag $DOCKER_HUB_USER_ID/account-service:$CIRCLE_SHA1 $DOCKER_HUB_USER_ID/account-service:latest
            docker push $DOCKER_HUB_USER_ID/account-service:$SHORT_GIT_HASH
            docker push $DOCKER_HUB_USER_ID/account-service:latest
